apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadcsfp6256-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadcsfp6256-tenant-component
    app.kubernetes.io/part-of: loadcsfp6256-tenant-app
  name: loadcsfp6256-tenant-component
  namespace: loadcsfp6256-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadcsfp6256-tenant-component
    weight: null
status: {}
